<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lab 2b: Digitizing Field Data (QGIS) – Introduction to GIS for Public Health</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-32274054a8f542ea3c2f2c25644db23c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="robots" content="noindex, nofollow, noarchive, nosnippet">
<meta name="googlebot" content="noindex, nofollow">


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Intro GIS for Public Health</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-sessions" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Sessions</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-sessions">    
        <li>
    <a class="dropdown-item" href="../sessions/day1.html">
 <span class="dropdown-text">Day 1: Introduction to GIS</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../sessions/day2.html">
 <span class="dropdown-text">Day 2: Projections &amp; Data Entry</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../sessions/day3.html">
 <span class="dropdown-text">Day 3: Data Management &amp; Spatial Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../sessions/day4.html">
 <span class="dropdown-text">Day 4: Network Analysis, Geocoding &amp; Raster</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../sessions/day5.html">
 <span class="dropdown-text">Day 5: Spatial Estimation &amp; Map Design</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../labs/index.html"> 
<span class="menu-text">Labs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../readings.html"> 
<span class="menu-text">Readings</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resources.html"> 
<span class="menu-text">Resources</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../setup.html"> 
<span class="menu-text">Setup</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#public-health-question" id="toc-public-health-question" class="nav-link active" data-scroll-target="#public-health-question">Public health question</a></li>
  <li><a href="#what-you-will-learn" id="toc-what-you-will-learn" class="nav-link" data-scroll-target="#what-you-will-learn">What you will learn</a></li>
  <li><a href="#what-you-will-produce" id="toc-what-you-will-produce" class="nav-link" data-scroll-target="#what-you-will-produce">What you will produce</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a>
  <ul class="collapse">
  <li><a href="#walking-audit-attribute-codebook" id="toc-walking-audit-attribute-codebook" class="nav-link" data-scroll-target="#walking-audit-attribute-codebook">Walking-audit attribute codebook</a></li>
  </ul></li>
  <li><a href="#before-you-begin" id="toc-before-you-begin" class="nav-link" data-scroll-target="#before-you-begin">Before you begin</a></li>
  <li><a href="#part-1-ai-assisted-codebook-design" id="toc-part-1-ai-assisted-codebook-design" class="nav-link" data-scroll-target="#part-1-ai-assisted-codebook-design">Part 1: AI-assisted codebook design</a></li>
  <li><a href="#part-2-create-a-project-and-add-imagery" id="toc-part-2-create-a-project-and-add-imagery" class="nav-link" data-scroll-target="#part-2-create-a-project-and-add-imagery">Part 2: Create a project and add imagery</a></li>
  <li><a href="#part-3-create-geopackage-layers" id="toc-part-3-create-geopackage-layers" class="nav-link" data-scroll-target="#part-3-create-geopackage-layers">Part 3: Create GeoPackage layers</a>
  <ul class="collapse">
  <li><a href="#a.-audit_sites-points" id="toc-a.-audit_sites-points" class="nav-link" data-scroll-target="#a.-audit_sites-points">3A. audit_sites (points)</a></li>
  <li><a href="#b.-street_segments-lines" id="toc-b.-street_segments-lines" class="nav-link" data-scroll-target="#b.-street_segments-lines">3B. street_segments (lines)</a></li>
  <li><a href="#c.-study_area-polygon" id="toc-c.-study_area-polygon" class="nav-link" data-scroll-target="#c.-study_area-polygon">3C. study_area (polygon)</a></li>
  </ul></li>
  <li><a href="#part-4-configure-snapping" id="toc-part-4-configure-snapping" class="nav-link" data-scroll-target="#part-4-configure-snapping">Part 4: Configure snapping</a></li>
  <li><a href="#part-5-digitize-the-study-area-polygon" id="toc-part-5-digitize-the-study-area-polygon" class="nav-link" data-scroll-target="#part-5-digitize-the-study-area-polygon">Part 5: Digitize the study-area polygon</a></li>
  <li><a href="#part-6-digitize-street-segments" id="toc-part-6-digitize-street-segments" class="nav-link" data-scroll-target="#part-6-digitize-street-segments">Part 6: Digitize street segments</a></li>
  <li><a href="#part-7-digitize-audit-observation-points" id="toc-part-7-digitize-audit-observation-points" class="nav-link" data-scroll-target="#part-7-digitize-audit-observation-points">Part 7: Digitize audit observation points</a></li>
  <li><a href="#part-8-field-calculator-lengths-areas-and-coordinates" id="toc-part-8-field-calculator-lengths-areas-and-coordinates" class="nav-link" data-scroll-target="#part-8-field-calculator-lengths-areas-and-coordinates">Part 8: Field Calculator — lengths, areas, and coordinates</a></li>
  <li><a href="#part-9-export-a-print-layout" id="toc-part-9-export-a-print-layout" class="nav-link" data-scroll-target="#part-9-export-a-print-layout">Part 9: Export a Print Layout</a></li>
  <li><a href="#deliverables" id="toc-deliverables" class="nav-link" data-scroll-target="#deliverables">Deliverables</a></li>
  <li><a href="#using-ai-in-this-lab" id="toc-using-ai-in-this-lab" class="nav-link" data-scroll-target="#using-ai-in-this-lab">Using AI in this lab</a></li>
  <li><a href="#arcgis-equivalents" id="toc-arcgis-equivalents" class="nav-link" data-scroll-target="#arcgis-equivalents">ArcGIS equivalents</a></li>
  <li><a href="#check-your-understanding" id="toc-check-your-understanding" class="nav-link" data-scroll-target="#check-your-understanding">Check your understanding</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/aquistbe/UHC-Summer-Institute-IntroGIS-2026/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab 2b: Digitizing Field Data (QGIS)</h1>
<p class="subtitle lead">Intro GIS for Public Health · QGIS track · Day 2</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="lab-download">
<p><a href="downloads/Lab02b_Digitizing_QGIS_PH.docx" class="btn btn-primary btn-sm" download="Lab02b_Digitizing_QGIS_PH.docx">Download this lab (Word)</a> <a href="../labs/lab2b-online.html" class="btn btn-outline-primary btn-sm">ArcGIS Online version</a> <a href="downloads/Lab02b_Digitizing_ArcGISPro_PH.docx" class="btn btn-outline-secondary btn-sm" download="Lab02b_Digitizing_ArcGISPro_PH.docx">ArcGIS Pro version (Word)</a></p>
</div>
<section id="public-health-question" class="level2">
<h2 class="anchored" data-anchor-id="public-health-question">Public health question</h2>
<p>A community health team is conducting a walking audit of four city blocks in West Philadelphia to assess pedestrian injury risk. Observations about sidewalk quality, crossing infrastructure, and traffic calming have been recorded on paper forms. To analyze the spatial distribution of hazardous conditions, those records must enter a GIS as georeferenced features. This lab teaches you to digitize point observations, street-segment lines, and a study-area polygon — and to record coded attributes — so the data can be mapped, queried, and linked to injury outcomes.</p>
<hr>
</section>
<section id="what-you-will-learn" class="level2">
<h2 class="anchored" data-anchor-id="what-you-will-learn">What you will learn</h2>
<ul>
<li>Add an imagery basemap using XYZ Tiles in the Browser panel</li>
<li>Create GeoPackage layers (point, line, polygon) with defined fields via <strong>Layer ▸ Create Layer ▸ New GeoPackage Layer</strong></li>
<li>Configure <strong>Value Map</strong> widgets for coded audit categories via <strong>Properties ▸ Attributes Form</strong></li>
<li>Set up snapping (<strong>Project ▸ Snapping Options</strong>) and toggle editing with the pencil icon</li>
<li>Digitize point, line, and polygon features; enter attributes in the form</li>
<li>Edit vertices with the <strong>Vertex Tool</strong></li>
<li>Populate length, area, and coordinate fields using the <strong>Field Calculator</strong> with <code>$length</code>, <code>$area</code>, and <code>transform()</code> expressions in a projected CRS</li>
<li>Export a <strong>Print Layout</strong> PDF</li>
</ul>
<hr>
</section>
<section id="what-you-will-produce" class="level2">
<h2 class="anchored" data-anchor-id="what-you-will-produce">What you will produce</h2>
<ol type="1">
<li>A GeoPackage (<code>Lab02b_WalkingAudit.gpkg</code>) with three layers: <code>audit_sites</code> (points), <code>street_segments</code> (lines), <code>study_area</code> (polygon)</li>
<li>Fully populated attribute tables for all three layers</li>
<li>An exported Print Layout PDF showing all three layers over imagery</li>
</ol>
<hr>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>All data are created by you during the session. No pre-existing GIS files are required.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Layer</th>
<th>Description</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OpenStreetMap (basemap)</td>
<td>Street reference</td>
<td>XYZ Tiles in the QGIS Browser panel</td>
</tr>
<tr class="even">
<td>Google Hybrid (imagery)</td>
<td>Aerial imagery for digitizing</td>
<td>XYZ Tiles — new connection (URL in Part 2)</td>
</tr>
<tr class="odd">
<td>Walking-audit codebook</td>
<td>Coded attribute categories</td>
<td>This handout</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Note:</strong> QGIS is free and open-source. There are no license fees, credits, or organizational account barriers.</p>
</blockquote>
<section id="walking-audit-attribute-codebook" class="level3">
<h3 class="anchored" data-anchor-id="walking-audit-attribute-codebook">Walking-audit attribute codebook</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Field name</th>
<th>Type</th>
<th>Coded values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Site ID</td>
<td><code>site_id</code></td>
<td>Integer</td>
<td>1, 2, 3 … (sequential)</td>
</tr>
<tr class="even">
<td>Lighting</td>
<td><code>lighting</code></td>
<td>Text (10)</td>
<td><code>none</code> · <code>poor</code> · <code>adequate</code></td>
</tr>
<tr class="odd">
<td>Sidewalk condition</td>
<td><code>sidewalk</code></td>
<td>Text (10)</td>
<td><code>good</code> · <code>cracked</code> · <code>absent</code></td>
</tr>
<tr class="even">
<td>Crossing aids</td>
<td><code>crossing</code></td>
<td>Text (10)</td>
<td><code>none</code> · <code>marked</code> · <code>signal</code> · <code>curb_ramp</code></td>
</tr>
<tr class="odd">
<td>Traffic calming</td>
<td><code>traffic_calm</code></td>
<td>Text (15)</td>
<td><code>none</code> · <code>speed_hump</code> · <code>bumpout</code></td>
</tr>
<tr class="even">
<td>Notes</td>
<td><code>notes</code></td>
<td>Text (100)</td>
<td>Free text</td>
</tr>
<tr class="odd">
<td>Segment ID</td>
<td><code>seg_id</code></td>
<td>Integer</td>
<td>Lines only</td>
</tr>
<tr class="even">
<td>Length (ft)</td>
<td><code>length_ft</code></td>
<td>Double</td>
<td>Calculated — lines</td>
</tr>
<tr class="odd">
<td>Area (sq ft)</td>
<td><code>area_sqft</code></td>
<td>Double</td>
<td>Calculated — polygon</td>
</tr>
<tr class="even">
<td>Latitude</td>
<td><code>lat_dd</code></td>
<td>Double</td>
<td>Calculated — points</td>
</tr>
<tr class="odd">
<td>Longitude</td>
<td><code>lon_dd</code></td>
<td>Double</td>
<td>Calculated — points</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Public health note:</strong> Coded values prevent free-text inconsistencies — a common data quality problem when multiple field workers contribute records. Consistent coding is essential for counting exposures across a study area.</p>
</blockquote>
<hr>
</section>
</section>
<section id="before-you-begin" class="level2">
<h2 class="anchored" data-anchor-id="before-you-begin">Before you begin</h2>
<p><strong>Prerequisites:</strong> Lab 1 (QGIS orientation) and Lab 2a (projections).</p>
<p><strong>QGIS version:</strong> QGIS 3.34 LTR — free at <a href="https://qgis.org">qgis.org</a>. No credits or licensing required.</p>
<p><strong>Plugins:</strong> Optional — install <strong>QuickMapServices</strong> (<strong>Plugins ▸ Manage and Install Plugins…</strong>) for one-click basemap access.</p>
<p><strong>Estimated time:</strong> 2 hours.</p>
<hr>
</section>
<section id="part-1-ai-assisted-codebook-design" class="level2">
<h2 class="anchored" data-anchor-id="part-1-ai-assisted-codebook-design">Part 1: AI-assisted codebook design</h2>
<ol type="1">
<li><p>Open Claude (claude.ai) or another approved AI assistant.</p></li>
<li><p>Paste this prompt exactly:</p>
<blockquote class="blockquote">
<p><em>“We’re auditing 4 blocks in West Philly to study pedestrian injury risk. We need to capture sidewalk quality, crossing infrastructure, and traffic calming. Draft a simple field codebook — field name, description, and coded values — for a GIS attribute table.”</em></p>
</blockquote></li>
<li><p>Compare the AI output to the codebook table above. Note matches, differences, and missing categories.</p></li>
<li><p>Write two sentences explaining one change you would make to the AI draft and why. Save as <code>codebook_notes.txt</code>.</p></li>
</ol>
<blockquote class="blockquote">
<p><strong>Using AI in this lab:</strong> The AI provides a starting scaffold. You, as the public health professional, decide which categories fit a pedestrian-injury study. The AI does not know your study population, IRB protocol, or local conditions. Always review and refine AI-generated protocols before research use.</p>
</blockquote>
<hr>
</section>
<section id="part-2-create-a-project-and-add-imagery" class="level2">
<h2 class="anchored" data-anchor-id="part-2-create-a-project-and-add-imagery">Part 2: Create a project and add imagery</h2>
<ol type="1">
<li><p><strong>Project ▸ New</strong>. Set the project CRS: click the CRS button at the bottom-right of the window, search <code>2272</code>, and select <strong>NAD83 / Pennsylvania South (ftUS)</strong>. Click <strong>OK</strong>.</p>
<blockquote class="blockquote">
<p><strong>Public health note:</strong> EPSG:2272 uses US feet. Setting this before digitizing means <code>$length</code> and <code>$area</code> in the Field Calculator return feet and square feet directly — matching your audit forms.</p>
</blockquote></li>
<li><p>Save the project: <strong>Project ▸ Save As…</strong> → <code>Lab02b_WalkingAudit.qgz</code> in your <code>Lab02b</code> folder.</p></li>
<li><p>In the <strong>Browser</strong> panel, expand <strong>XYZ Tiles</strong> and double-click <strong>OpenStreetMap</strong> to add it.</p></li>
<li><p>Right-click <strong>XYZ Tiles ▸ New Connection…</strong>. Set <strong>Name</strong> to <code>Google Hybrid</code> and <strong>URL</strong> to <code>https://mt1.google.com/vt/lyrs=y&amp;x={x}&amp;y={y}&amp;z={z}</code>. Click <strong>OK</strong>, then double-click the new connection to add imagery to the map.</p></li>
<li><p>Navigate to West Philadelphia — zoom to approximately 40th Street and Baltimore Avenue.</p></li>
</ol>
<p><em>[Figure: QGIS map canvas at ~1:5,000 showing West Philadelphia imagery with Layers panel visible]</em></p>
<hr>
</section>
<section id="part-3-create-geopackage-layers" class="level2">
<h2 class="anchored" data-anchor-id="part-3-create-geopackage-layers">Part 3: Create GeoPackage layers</h2>
<p>GeoPackage (<code>.gpkg</code>) is QGIS’s preferred open format — a single file that holds multiple layers, free of the shapefile’s field-length limits.</p>
<section id="a.-audit_sites-points" class="level3">
<h3 class="anchored" data-anchor-id="a.-audit_sites-points">3A. audit_sites (points)</h3>
<ol type="1">
<li><p><strong>Layer ▸ Create Layer ▸ New GeoPackage Layer…</strong></p></li>
<li><p>Click <strong>…</strong> next to Database, navigate to <code>Lab02b</code>, name the file <code>Lab02b_WalkingAudit.gpkg</code>. <strong>Table name:</strong> <code>audit_sites</code>. <strong>Geometry type:</strong> Point. <strong>CRS:</strong> EPSG:2272.</p></li>
<li><p>Add each field using the <strong>New Field</strong> section and clicking <strong>Add to Fields List</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field name</th>
<th>Type</th>
<th>Length</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>site_id</code></td>
<td>Integer</td>
<td>—</td>
</tr>
<tr class="even">
<td><code>lighting</code></td>
<td>Text (string)</td>
<td>10</td>
</tr>
<tr class="odd">
<td><code>sidewalk</code></td>
<td>Text (string)</td>
<td>10</td>
</tr>
<tr class="even">
<td><code>crossing</code></td>
<td>Text (string)</td>
<td>10</td>
</tr>
<tr class="odd">
<td><code>traffic_calm</code></td>
<td>Text (string)</td>
<td>15</td>
</tr>
<tr class="even">
<td><code>notes</code></td>
<td>Text (string)</td>
<td>100</td>
</tr>
<tr class="odd">
<td><code>lat_dd</code></td>
<td>Decimal number</td>
<td>—</td>
</tr>
<tr class="even">
<td><code>lon_dd</code></td>
<td>Decimal number</td>
<td>—</td>
</tr>
</tbody>
</table></li>
<li><p>Click <strong>OK</strong>. The layer appears in the Layers panel.</p></li>
</ol>
<p><strong>Configure Value Map widgets:</strong> Right-click <code>audit_sites</code> → <strong>Properties ▸ Attributes Form</strong>. Select <code>lighting</code>; change Widget type to <strong>Value Map</strong>. Add rows for each coded value (<code>none</code>, <code>poor</code>, <code>adequate</code>). Repeat for <code>sidewalk</code>, <code>crossing</code>, and <code>traffic_calm</code>.</p>
<p><em>[Figure: Attributes Form tab showing Value Map widget for the lighting field]</em></p>
</section>
<section id="b.-street_segments-lines" class="level3">
<h3 class="anchored" data-anchor-id="b.-street_segments-lines">3B. street_segments (lines)</h3>
<ol type="1">
<li><strong>Layer ▸ Create Layer ▸ New GeoPackage Layer…</strong> — select the existing <code>Lab02b_WalkingAudit.gpkg</code> as the database (do not create a new file). <strong>Table name:</strong> <code>street_segments</code>. <strong>Geometry type:</strong> Line String. <strong>CRS:</strong> EPSG:2272.</li>
<li>Add fields: <code>seg_id</code> (Integer), <code>lighting</code>/<code>sidewalk</code>/<code>crossing</code>/<code>traffic_calm</code> (Text, same lengths as above), <code>notes</code> (Text 100), <code>length_ft</code> (Decimal).</li>
<li>Configure Value Map widgets for the four coded fields.</li>
</ol>
</section>
<section id="c.-study_area-polygon" class="level3">
<h3 class="anchored" data-anchor-id="c.-study_area-polygon">3C. study_area (polygon)</h3>
<ol type="1">
<li>Same process — <strong>Table name:</strong> <code>study_area</code>. <strong>Geometry type:</strong> Polygon. <strong>CRS:</strong> EPSG:2272.</li>
<li>Add one field: <code>area_sqft</code> (Decimal number). Click <strong>OK</strong>.</li>
</ol>
<hr>
</section>
</section>
<section id="part-4-configure-snapping" class="level2">
<h2 class="anchored" data-anchor-id="part-4-configure-snapping">Part 4: Configure snapping</h2>
<ol type="1">
<li><strong>Project ▸ Snapping Options…</strong> (or click the magnet icon on the Snapping toolbar).</li>
<li>Activate snapping (click the horseshoe magnet so it darkens). Set <strong>Mode:</strong> All Layers; enable <strong>Vertex</strong> and <strong>Segment</strong>; set tolerance to <strong>10 feet</strong>.</li>
<li>Enable <strong>Topological Editing</strong> so that moving a shared vertex updates all connected features.</li>
</ol>
<blockquote class="blockquote">
<p><strong>Note:</strong> 10 feet suits block-scale data. Too small causes missed connections; too large forces unintended snapping.</p>
</blockquote>
<hr>
</section>
<section id="part-5-digitize-the-study-area-polygon" class="level2">
<h2 class="anchored" data-anchor-id="part-5-digitize-the-study-area-polygon">Part 5: Digitize the study-area polygon</h2>
<ol type="1">
<li>Select <code>study_area</code> in the Layers panel. Click the <strong>pencil (Toggle Editing)</strong> icon.</li>
<li>Set a semi-transparent fill so imagery remains visible: <strong>Properties ▸ Symbology ▸ Simple Fill</strong> → set <strong>Opacity</strong> to 50% in the Layer Rendering section.</li>
<li>Click <strong>Add Polygon Feature</strong>. Click the four-to-six street corners defining the study boundary. <strong>Right-click</strong> to finish. Leave <code>area_sqft</code> blank. Click <strong>OK</strong> in the attribute form.</li>
<li><strong>Save Layer Edits</strong> (floppy disk icon).</li>
</ol>
<p><strong>To adjust a vertex:</strong> press V for the <strong>Vertex Tool</strong>, click a vertex (turns blue), drag. Double-click an edge to insert a new vertex.</p>
<hr>
</section>
<section id="part-6-digitize-street-segments" class="level2">
<h2 class="anchored" data-anchor-id="part-6-digitize-street-segments">Part 6: Digitize street segments</h2>
<ol type="1">
<li>Select <code>street_segments</code>, toggle editing on. Click <strong>Add Line Feature</strong>.</li>
<li>Left-click along one block face to place vertices. <strong>Right-click</strong> to finish. In the attribute form, enter <code>seg_id</code>, coded values for the four audit fields, and a note. Leave <code>length_ft</code> blank.</li>
<li>Digitize at least <strong>four block faces</strong>. The snap indicator confirms vertex coincidence at existing endpoints.</li>
<li>Mid-digitize: press <strong>Backspace</strong> to remove the last vertex; <strong>Escape</strong> to abandon the segment.</li>
<li>To edit a finished segment, use the <strong>Vertex Tool</strong> (V): click a vertex and drag; double-click an edge to insert a vertex.</li>
<li>Save layer edits.</li>
</ol>
<p><em>[Figure: Map showing four line segments along West Philadelphia block faces, with snap indicator visible at an intersection]</em></p>
<hr>
</section>
<section id="part-7-digitize-audit-observation-points" class="level2">
<h2 class="anchored" data-anchor-id="part-7-digitize-audit-observation-points">Part 7: Digitize audit observation points</h2>
<ol type="1">
<li>Select <code>audit_sites</code>, toggle editing on. Click <strong>Add Point Feature</strong>.</li>
<li>Left-click a sidewalk location. In the attribute form, enter <code>site_id</code>, coded values, and notes. Leave <code>lat_dd</code>/<code>lon_dd</code> blank. Click <strong>OK</strong>.</li>
<li>Digitize at least <strong>six points</strong> distributed across the study area, mixing good and poor conditions.</li>
</ol>
<blockquote class="blockquote">
<p><strong>Warning:</strong> To remove a misplaced point immediately, press <strong>Ctrl+Z</strong> (Undo). To delete a saved point, activate <strong>Select Features</strong> (yellow arrow), click the point, then press <strong>Delete</strong>.</p>
</blockquote>
<ol start="4" type="1">
<li>To move a point, use <strong>Edit ▸ Move Feature(s)</strong>: click the point, then click the corrected location.</li>
<li>Save layer edits. Then save the project (Ctrl+S).</li>
</ol>
<blockquote class="blockquote">
<p><strong>Mobile collection note:</strong> <strong>QField</strong> (qfield.cloud) syncs your <code>.qgz</code> project, GeoPackage layers, and Value Map widgets to a tablet or phone for GPS-enabled field data collection.</p>
</blockquote>
<p><em>[Figure: Map showing six point symbols over West Philadelphia imagery, attribute form open with value-map drop-downs visible]</em></p>
<hr>
</section>
<section id="part-8-field-calculator-lengths-areas-and-coordinates" class="level2">
<h2 class="anchored" data-anchor-id="part-8-field-calculator-lengths-areas-and-coordinates">Part 8: Field Calculator — lengths, areas, and coordinates</h2>
<p>Open the attribute table (<strong>F6</strong>), click the <strong>Field Calculator</strong> (abacus icon), check <strong>Update existing field</strong>, select the target field, and enter the expression below.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Layer</th>
<th>Field</th>
<th>Expression</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>street_segments</code></td>
<td><code>length_ft</code></td>
<td><code>$length</code></td>
</tr>
<tr class="even">
<td><code>study_area</code></td>
<td><code>area_sqft</code></td>
<td><code>$area</code></td>
</tr>
<tr class="odd">
<td><code>audit_sites</code></td>
<td><code>lat_dd</code></td>
<td><code>y(transform($geometry, 'EPSG:2272', 'EPSG:4326'))</code></td>
</tr>
<tr class="even">
<td><code>audit_sites</code></td>
<td><code>lon_dd</code></td>
<td><code>x(transform($geometry, 'EPSG:2272', 'EPSG:4326'))</code></td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Note:</strong> <code>$length</code> and <code>$area</code> return values in the layer CRS units (feet, because EPSG:2272 uses US feet). Plain <code>$y</code> would return northing in feet, not latitude — so <code>transform()</code> to WGS84 is needed for decimal-degree coordinates.</p>
</blockquote>
<p>Verify: latitude ≈ 39.95, longitude ≈ −75.20. Values well outside that range indicate a CRS mismatch. Save all layer edits, then save the project (Ctrl+S).</p>
<hr>
</section>
<section id="part-9-export-a-print-layout" class="level2">
<h2 class="anchored" data-anchor-id="part-9-export-a-print-layout">Part 9: Export a Print Layout</h2>
<ol type="1">
<li><strong>Project ▸ New Print Layout…</strong>, name it, click <strong>OK</strong>.</li>
<li><strong>Add Item ▸ Add Map</strong> — draw a frame across most of the page.</li>
<li>Add: <strong>Label</strong> (title: <em>Walking Audit — West Philadelphia Study Area</em>), <strong>Legend</strong>, <strong>Scale Bar</strong> (feet), <strong>North Arrow</strong>, and a Label with your name and date.</li>
<li><strong>Layout ▸ Export as PDF…</strong> → save as <code>Lab02b_map.pdf</code>.</li>
</ol>
<hr>
</section>
<section id="deliverables" class="level2">
<h2 class="anchored" data-anchor-id="deliverables">Deliverables</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>File</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Lab02b_WalkingAudit.gpkg</code> (zipped)</td>
<td>GeoPackage with all three layers and populated attributes</td>
</tr>
<tr class="even">
<td><code>Lab02b_WalkingAudit.qgz</code></td>
<td>QGIS project file</td>
</tr>
<tr class="odd">
<td><code>Lab02b_map.pdf</code></td>
<td>Print Layout export showing all layers over imagery</td>
</tr>
<tr class="even">
<td><code>codebook_notes.txt</code></td>
<td>Two-sentence reflection from Part 1; note AI origin and your revision</td>
</tr>
<tr class="odd">
<td>Short interpretation (100 words)</td>
<td>Which block face or intersection is most hazardous, and which two coded conditions drove that judgment? (Submit as a text block in the PDF or a separate <code>.txt</code>)</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="using-ai-in-this-lab" class="level2">
<h2 class="anchored" data-anchor-id="using-ai-in-this-lab">Using AI in this lab</h2>
<p><strong>Permitted (Part 1):</strong> Draft an audit codebook from a 3-sentence description, then evaluate and refine it as the subject-matter expert.</p>
<p><strong>Guardrails that always apply:</strong></p>
<ul>
<li>AI assists with <strong>scaffolding</strong>, <strong>explaining</strong>, and <strong>critiquing</strong> — not analytic decisions, feature selection, or interpretation of field observations.</li>
<li>Never paste PHI or identifiable addresses into a public LLM. This lab uses illustrative data, but build the habit now.</li>
<li>Label all AI-assisted output. In <code>codebook_notes.txt</code>, state the draft was AI-generated and describe your revision.</li>
<li>You may ask AI to help write or debug a Field Calculator expression; always test the result on your own data.</li>
</ul>
<hr>
</section>
<section id="arcgis-equivalents" class="level2">
<h2 class="anchored" data-anchor-id="arcgis-equivalents">ArcGIS equivalents</h2>
<p>The matching <strong>ArcGIS Pro</strong> version (Lab 2b Pro) and an <strong>ArcGIS Online</strong> version exist for those platforms.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>QGIS (this lab)</th>
<th>ArcGIS Pro equivalent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Layer ▸ Create Layer ▸ New GeoPackage Layer</strong></td>
<td>Create Feature Class wizard (in a file geodatabase)</td>
</tr>
<tr class="even">
<td>Pencil icon → Add Point / Line / Polygon Feature</td>
<td><strong>Edit</strong> tab → <strong>Create Features</strong> panel</td>
</tr>
<tr class="odd">
<td><strong>Project ▸ Snapping Options</strong></td>
<td><strong>Edit</strong> tab → Snapping group → Snapping toggle</td>
</tr>
<tr class="even">
<td><strong>Vertex Tool</strong></td>
<td><strong>Modify Features</strong> → Vertices</td>
</tr>
<tr class="odd">
<td><strong>Field Calculator</strong> with <code>$length</code>, <code>$area</code>, <code>transform()</code></td>
<td>Right-click column → <strong>Calculate Geometry</strong></td>
</tr>
<tr class="even">
<td><strong>Save Layer Edits</strong> (floppy disk)</td>
<td><strong>Edit</strong> tab → <strong>Save</strong> (Manage Edits)</td>
</tr>
<tr class="odd">
<td><strong>Project ▸ New Print Layout</strong></td>
<td><strong>Insert</strong> tab → <strong>New Layout</strong></td>
</tr>
<tr class="even">
<td>GeoPackage (<code>.gpkg</code>)</td>
<td>File geodatabase (<code>.gdb</code>)</td>
</tr>
<tr class="odd">
<td>Value Map widget (Attributes Form)</td>
<td>Coded-value domain</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="check-your-understanding" class="level2">
<h2 class="anchored" data-anchor-id="check-your-understanding">Check your understanding</h2>
<ol type="1">
<li>Why set the project CRS to EPSG:2272 before digitizing, rather than leaving it in WGS84?</li>
<li>What data quality problem could arise in a multi-auditor study if <code>sidewalk</code> is a plain text field rather than a Value Map widget?</li>
<li>List the exact steps to use the Vertex Tool in QGIS to move an incorrect vertex on a finished line segment.</li>
<li>A colleague’s <code>street_segments</code> layer was accidentally created with CRS EPSG:4326. What units would <code>$length</code> return, and why would the values look wrong?</li>
<li>A colleague proposes skipping the study-area polygon and using the bounding extent of points and lines instead. What analytic problem arises when calculating the percentage of block faces with absent sidewalks?</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/aquistbe\.github\.io\/UHC-Summer-Institute-IntroGIS-2026\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Introduction to GIS for Public Health | Urban Health Summer Institute</p>
</div>   
    <div class="nav-footer-center">
<p>Drexel University Dornsife School of Public Health</p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/aquistbe/UHC-Summer-Institute-IntroGIS-2026/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>© 2026 Alex Quistberg</p>
</div>
  </div>
</footer>




</body></html>