<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lab 2a: Projections Done Right (QGIS) – Introduction to GIS for Public Health</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-32274054a8f542ea3c2f2c25644db23c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="robots" content="noindex, nofollow, noarchive, nosnippet">
<meta name="googlebot" content="noindex, nofollow">


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Intro GIS for Public Health</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-sessions" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Sessions</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-sessions">    
        <li>
    <a class="dropdown-item" href="../sessions/day1.html">
 <span class="dropdown-text">Day 1: Introduction to GIS</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../sessions/day2.html">
 <span class="dropdown-text">Day 2: Projections &amp; Data Entry</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../sessions/day3.html">
 <span class="dropdown-text">Day 3: Data Management &amp; Spatial Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../sessions/day4.html">
 <span class="dropdown-text">Day 4: Network Analysis, Geocoding &amp; Raster</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../sessions/day5.html">
 <span class="dropdown-text">Day 5: Spatial Estimation &amp; Map Design</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../labs/index.html"> 
<span class="menu-text">Labs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../readings.html"> 
<span class="menu-text">Readings</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resources.html"> 
<span class="menu-text">Resources</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../setup.html"> 
<span class="menu-text">Setup</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#public-health-question" id="toc-public-health-question" class="nav-link active" data-scroll-target="#public-health-question">Public health question</a></li>
  <li><a href="#what-you-will-learn" id="toc-what-you-will-learn" class="nav-link" data-scroll-target="#what-you-will-learn">What you will learn</a></li>
  <li><a href="#what-you-will-produce" id="toc-what-you-will-produce" class="nav-link" data-scroll-target="#what-you-will-produce">What you will produce</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#before-you-begin" id="toc-before-you-begin" class="nav-link" data-scroll-target="#before-you-begin">Before you begin</a></li>
  <li><a href="#part-1-create-the-project-and-inspect-layer-coordinate-systems" id="toc-part-1-create-the-project-and-inspect-layer-coordinate-systems" class="nav-link" data-scroll-target="#part-1-create-the-project-and-inspect-layer-coordinate-systems">Part 1: Create the project and inspect layer coordinate systems</a>
  <ul class="collapse">
  <li><a href="#set-up-the-project" id="toc-set-up-the-project" class="nav-link" data-scroll-target="#set-up-the-project">Set up the project</a></li>
  <li><a href="#check-each-layers-crs" id="toc-check-each-layers-crs" class="nav-link" data-scroll-target="#check-each-layers-crs">Check each layer’s CRS</a></li>
  <li><a href="#look-up-crs-codes-on-epsg.io" id="toc-look-up-crs-codes-on-epsg.io" class="nav-link" data-scroll-target="#look-up-crs-codes-on-epsg.io">Look up CRS codes on epsg.io</a></li>
  </ul></li>
  <li><a href="#part-2-run-a-buffer-in-the-wrong-coordinate-system-wgs84" id="toc-part-2-run-a-buffer-in-the-wrong-coordinate-system-wgs84" class="nav-link" data-scroll-target="#part-2-run-a-buffer-in-the-wrong-coordinate-system-wgs84">Part 2: Run a buffer in the wrong coordinate system (WGS84)</a>
  <ul class="collapse">
  <li><a href="#confirm-the-project-crs-is-wgs84" id="toc-confirm-the-project-crs-is-wgs84" class="nav-link" data-scroll-target="#confirm-the-project-crs-is-wgs84">Confirm the project CRS is WGS84</a></li>
  <li><a href="#run-the-buffer-in-degrees" id="toc-run-the-buffer-in-degrees" class="nav-link" data-scroll-target="#run-the-buffer-in-degrees">Run the Buffer in degrees</a></li>
  <li><a href="#use-the-measure-tool-to-document-the-distortion" id="toc-use-the-measure-tool-to-document-the-distortion" class="nav-link" data-scroll-target="#use-the-measure-tool-to-document-the-distortion">Use the Measure tool to document the distortion</a></li>
  </ul></li>
  <li><a href="#part-3-reproject-the-data-and-run-the-buffer-correctly" id="toc-part-3-reproject-the-data-and-run-the-buffer-correctly" class="nav-link" data-scroll-target="#part-3-reproject-the-data-and-run-the-buffer-correctly">Part 3: Reproject the data and run the buffer correctly</a>
  <ul class="collapse">
  <li><a href="#permanently-reproject-to-pa-state-plane-south-epsg2272" id="toc-permanently-reproject-to-pa-state-plane-south-epsg2272" class="nav-link" data-scroll-target="#permanently-reproject-to-pa-state-plane-south-epsg2272">Permanently reproject to PA State Plane South (EPSG:2272)</a></li>
  <li><a href="#verify-the-reprojection" id="toc-verify-the-reprojection" class="nav-link" data-scroll-target="#verify-the-reprojection">Verify the reprojection</a></li>
  <li><a href="#set-the-project-crs-to-epsg2272" id="toc-set-the-project-crs-to-epsg2272" class="nav-link" data-scroll-target="#set-the-project-crs-to-epsg2272">Set the project CRS to EPSG:2272</a></li>
  <li><a href="#run-the-buffer-in-feet" id="toc-run-the-buffer-in-feet" class="nav-link" data-scroll-target="#run-the-buffer-in-feet">Run the Buffer in feet</a></li>
  <li><a href="#measure-and-compare" id="toc-measure-and-compare" class="nav-link" data-scroll-target="#measure-and-compare">Measure and compare</a></li>
  </ul></li>
  <li><a href="#part-4-compare-the-two-buffers-in-a-print-layout" id="toc-part-4-compare-the-two-buffers-in-a-print-layout" class="nav-link" data-scroll-target="#part-4-compare-the-two-buffers-in-a-print-layout">Part 4: Compare the two buffers in a Print Layout</a></li>
  <li><a href="#part-5-estimate-children-with-park-access-by-poverty-quintile" id="toc-part-5-estimate-children-with-park-access-by-poverty-quintile" class="nav-link" data-scroll-target="#part-5-estimate-children-with-park-access-by-poverty-quintile">Part 5: Estimate children with park access by poverty quintile</a>
  <ul class="collapse">
  <li><a href="#prepare-tract-areas-for-areal-interpolation" id="toc-prepare-tract-areas-for-areal-interpolation" class="nav-link" data-scroll-target="#prepare-tract-areas-for-areal-interpolation">Prepare tract areas for areal interpolation</a></li>
  <li><a href="#intersect-the-correct-buffer-with-census-tracts" id="toc-intersect-the-correct-buffer-with-census-tracts" class="nav-link" data-scroll-target="#intersect-the-correct-buffer-with-census-tracts">Intersect the correct buffer with census tracts</a></li>
  <li><a href="#calculate-clipped-area-and-estimated-children-in-the-buffer" id="toc-calculate-clipped-area-and-estimated-children-in-the-buffer" class="nav-link" data-scroll-target="#calculate-clipped-area-and-estimated-children-in-the-buffer">Calculate clipped area and estimated children in the buffer</a></li>
  <li><a href="#summarize-by-poverty-quintile" id="toc-summarize-by-poverty-quintile" class="nav-link" data-scroll-target="#summarize-by-poverty-quintile">Summarize by poverty quintile</a></li>
  <li><a href="#apply-graduated-symbology-to-visualize-access-by-poverty-quintile" id="toc-apply-graduated-symbology-to-visualize-access-by-poverty-quintile" class="nav-link" data-scroll-target="#apply-graduated-symbology-to-visualize-access-by-poverty-quintile">Apply graduated symbology to visualize access by poverty quintile</a></li>
  </ul></li>
  <li><a href="#deliverables" id="toc-deliverables" class="nav-link" data-scroll-target="#deliverables">Deliverables</a></li>
  <li><a href="#using-ai-in-this-lab" id="toc-using-ai-in-this-lab" class="nav-link" data-scroll-target="#using-ai-in-this-lab">Using AI in this lab</a></li>
  <li><a href="#arcgis-equivalents" id="toc-arcgis-equivalents" class="nav-link" data-scroll-target="#arcgis-equivalents">ArcGIS equivalents</a></li>
  <li><a href="#check-your-understanding" id="toc-check-your-understanding" class="nav-link" data-scroll-target="#check-your-understanding">Check your understanding</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/aquistbe/UHC-Summer-Institute-IntroGIS-2026/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab 2a: Projections Done Right (QGIS)</h1>
<p class="subtitle lead">Intro GIS for Public Health · QGIS track · Day 2</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="lab-download">
<p><a href="downloads/Lab02a_Projections_QGIS_PH.docx" class="btn btn-primary btn-sm" download="Lab02a_Projections_QGIS_PH.docx">Download this lab (Word)</a> <a href="../labs/lab2a-online.html" class="btn btn-outline-primary btn-sm">ArcGIS Online version</a> <a href="downloads/Lab02a_Projections_ArcGISPro_PH.docx" class="btn btn-outline-secondary btn-sm" download="Lab02a_Projections_ArcGISPro_PH.docx">ArcGIS Pro version (Word)</a></p>
</div>
<section id="public-health-question" class="level2">
<h2 class="anchored" data-anchor-id="public-health-question">Public health question</h2>
<p>Philadelphia’s park system is a critical health resource, but proximity depends entirely on how you measure distance. This lab asks: what share of Philadelphia children live within a 0.5-mile walk of a public park? The answer differs dramatically depending on the coordinate system used to run the buffer. One result is valid; the other is geographic nonsense. Learning to identify and fix this error before it reaches analysis is a foundational GIS skill.</p>
<hr>
</section>
<section id="what-you-will-learn" class="level2">
<h2 class="anchored" data-anchor-id="what-you-will-learn">What you will learn</h2>
<ul>
<li>Distinguish geographic coordinate systems (GCS) from projected coordinate systems (PCS)</li>
<li>Check a layer’s CRS in <strong>Layer Properties ▸ Information</strong> and read the project CRS button at the bottom-right of the QGIS window</li>
<li>Interpret EPSG codes and look up unfamiliar CRS definitions at epsg.io</li>
<li>Understand that QGIS reprojects layers on the fly for display — and why that is not enough for distance analysis</li>
<li>Permanently reproject a layer using <strong>Export ▸ Save Features As…</strong> or the Processing <strong>Reproject Layer</strong> tool</li>
<li>Run a <strong>Buffer</strong> operation in both the wrong CRS (degrees) and the correct CRS (feet) and see the difference on the map</li>
<li>Use the <strong>Measure</strong> tool to document distance distortion across coordinate systems</li>
<li>Use <strong>Join attributes by location (summary)</strong> and the <strong>Field Calculator</strong> to estimate children with park access by census tract</li>
<li>Apply graduated symbology to display park access by poverty quintile</li>
<li>Build a two-panel <strong>Print Layout</strong> comparing the wrong and correct buffers</li>
</ul>
<hr>
</section>
<section id="what-you-will-produce" class="level2">
<h2 class="anchored" data-anchor-id="what-you-will-produce">What you will produce</h2>
<ol type="1">
<li><strong>Two-panel Print Layout PDF</strong> (<code>Lab02a_buffer_comparison.pdf</code>) showing the same city at the same scale — left panel: 0.5-degree WGS84 buffer (wrong); right panel: 2,640-foot State Plane buffer (correct) — with labeled titles, your name, a scale bar, and a north arrow.</li>
<li><strong>A summary table</strong> showing the percentage of children with park access (within the correct 0.5-mile buffer) by census-tract poverty quintile (five groups, lowest to highest poverty).</li>
<li><strong>A 100-word written interpretation</strong> comparing access equity across poverty quintiles and explaining why the WGS84 buffer is invalid for this analysis. Label any AI-assisted portions.</li>
<li><strong>Your saved QGIS project file</strong> (<code>Lab02a_Projections.qgz</code>).</li>
</ol>
<hr>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>All data are instructor-provided. Save them to your working folder before starting.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Layer name</th>
<th>Description</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>PPR_properties.shp</code></td>
<td>Philadelphia parks and recreation properties (polygons)</td>
<td>OpenDataPhilly</td>
</tr>
<tr class="even">
<td><code>phl_tracts_acs.shp</code></td>
<td>Philadelphia census tracts with ACS child population (<code>CHILD_POP</code>, field B09001) and poverty rate (<code>POV_RATE</code>); includes <code>POV_QUINTILE</code> (1 = lowest, 5 = highest poverty)</td>
<td>NHGIS / Census Bureau</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Note:</strong> Both layers are delivered in WGS84 (EPSG:4326). Your instructor will confirm exact field names for your data vintage. If a full-tract area field (<code>AREA_FULL</code>) is not present, you will calculate it in Part 4.</p>
</blockquote>
<hr>
</section>
<section id="before-you-begin" class="level2">
<h2 class="anchored" data-anchor-id="before-you-begin">Before you begin</h2>
<p><strong>QGIS is free and open-source.</strong> No license, credits, or organizational account required. Download QGIS 3.34 LTR from qgis.org if it is not already installed.</p>
<p><strong>Prerequisites:</strong> Completion of Lab 1 (opening a project, adding data, basic navigation). No prior knowledge of projections is assumed — this lab teaches that.</p>
<p><strong>Plugins needed:</strong> None for this lab. The tools used are all native to QGIS 3.34.</p>
<p><strong>Time estimate:</strong> 2.5 to 3 hours.</p>
<p><strong>Have ready before starting:</strong></p>
<ul>
<li>QGIS 3.34 LTR open</li>
<li>Your working folder with <code>PPR_properties.shp</code> and <code>phl_tracts_acs.shp</code></li>
<li>A web browser for epsg.io lookups</li>
</ul>
<hr>
</section>
<section id="part-1-create-the-project-and-inspect-layer-coordinate-systems" class="level2">
<h2 class="anchored" data-anchor-id="part-1-create-the-project-and-inspect-layer-coordinate-systems">Part 1: Create the project and inspect layer coordinate systems</h2>
<section id="set-up-the-project" class="level3">
<h3 class="anchored" data-anchor-id="set-up-the-project">Set up the project</h3>
<ol type="1">
<li>Open QGIS 3.34. Go to <strong>Project ▸ New</strong> (Ctrl+N) to create a blank project.</li>
<li>Go to <strong>Project ▸ Save As…</strong> Name the file <code>Lab02a_Projections</code> and save it to your working folder. QGIS creates a <code>.qgz</code> file.</li>
<li>Add your data: go to <strong>Layer ▸ Add Layer ▸ Add Vector Layer</strong>, click the <strong>…</strong> button, navigate to your working folder, and select <code>PPR_properties.shp</code>. Click <strong>Add</strong>, then repeat for <code>phl_tracts_acs.shp</code>. Alternatively, drag both files from the <strong>Browser</strong> panel directly onto the map canvas.</li>
</ol>
<p><em>[Figure: Layers panel showing PPR_properties and phl_tracts_acs loaded; both visible on the map canvas]</em></p>
</section>
<section id="check-each-layers-crs" class="level3">
<h3 class="anchored" data-anchor-id="check-each-layers-crs">Check each layer’s CRS</h3>
<ol start="4" type="1">
<li>In the <strong>Layers</strong> panel, right-click <code>phl_tracts_acs</code> and select <strong>Properties</strong>. Click the <strong>Information</strong> tab (or the <strong>Source</strong> tab in some builds). Look at the <strong>Coordinate Reference System</strong> line.</li>
<li>You should see <strong>EPSG:4326 — WGS 84</strong>. This is a geographic coordinate system — location stored in degrees (longitude/latitude), not feet or meters.</li>
<li>Click <strong>OK</strong>. Repeat for <code>PPR_properties</code>. Both layers should show EPSG:4326.</li>
</ol>
<p><em>[Figure: Layer Properties ▸ Information tab showing EPSG:4326 WGS 84 for phl_tracts_acs]</em></p>
<ol start="7" type="1">
<li>Look at the bottom-right corner of the QGIS window. You will see the project CRS button displaying <strong>EPSG:4326</strong>. QGIS automatically adopted the CRS of the first layer loaded. You can click this button at any time to open <strong>Project ▸ Properties ▸ CRS</strong>.</li>
</ol>
<blockquote class="blockquote">
<p><strong>Note:</strong> The <strong>project CRS</strong> and a <strong>layer’s stored CRS</strong> are separate. QGIS reprojects layers on the fly for display so they line up on screen, but the coordinates stored on disk are unchanged. For any analysis involving distance or area, you must work in a projected CRS with linear units — not degrees. This is a critical distinction that ArcGIS Online hides from you by computing geodesic distances automatically; QGIS does not do this for you.</p>
</blockquote>
</section>
<section id="look-up-crs-codes-on-epsg.io" class="level3">
<h3 class="anchored" data-anchor-id="look-up-crs-codes-on-epsg.io">Look up CRS codes on epsg.io</h3>
<ol start="8" type="1">
<li>Open a browser and go to <strong>epsg.io</strong>. Search each code below and confirm the listed units:</li>
</ol>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>EPSG</th>
<th>Name</th>
<th>Units</th>
<th>Use for Philadelphia?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4326</td>
<td>WGS 84</td>
<td>degrees</td>
<td>Display only — never for distance/area</td>
</tr>
<tr class="even">
<td>2272</td>
<td>NAD83 / Pennsylvania South</td>
<td>US survey foot</td>
<td>Yes — recommended for this lab</td>
</tr>
<tr class="odd">
<td>26918</td>
<td>NAD83 / UTM Zone 18N</td>
<td>metre</td>
<td>Yes — also acceptable</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Public health note:</strong> Any analysis involving distance or area — buffers, service areas, density calculations — requires a projected CRS with linear units (feet or meters). EPSG:4326 measures in degrees. Passing degrees to a distance tool produces meaningless results.</p>
</blockquote>
<hr>
</section>
</section>
<section id="part-2-run-a-buffer-in-the-wrong-coordinate-system-wgs84" class="level2">
<h2 class="anchored" data-anchor-id="part-2-run-a-buffer-in-the-wrong-coordinate-system-wgs84">Part 2: Run a buffer in the wrong coordinate system (WGS84)</h2>
<p>This part deliberately does the analysis wrong so you can see the consequence.</p>
<section id="confirm-the-project-crs-is-wgs84" class="level3">
<h3 class="anchored" data-anchor-id="confirm-the-project-crs-is-wgs84">Confirm the project CRS is WGS84</h3>
<ol type="1">
<li>Click the CRS button at the bottom-right of the window. Confirm it reads <strong>EPSG:4326 — WGS 84</strong>. If not, click <strong>Project ▸ Properties ▸ CRS</strong>, type <code>4326</code> in the filter box, select <strong>WGS 84</strong>, and click <strong>OK</strong>.</li>
</ol>
</section>
<section id="run-the-buffer-in-degrees" class="level3">
<h3 class="anchored" data-anchor-id="run-the-buffer-in-degrees">Run the Buffer in degrees</h3>
<ol start="2" type="1">
<li>Open the <strong>Processing Toolbox</strong> (<strong>Processing ▸ Toolbox</strong>, or Ctrl+Alt+T). In the search box at the top, type <code>buffer</code>. Double-click <strong>Buffer</strong> (under Vector geometry).</li>
<li>Set the parameters:</li>
</ol>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Input layer</td>
<td><code>PPR_properties</code></td>
</tr>
<tr class="even">
<td>Distance</td>
<td><code>0.5</code></td>
</tr>
<tr class="odd">
<td>Segments</td>
<td>5</td>
</tr>
<tr class="even">
<td>Dissolve result</td>
<td>Checked</td>
</tr>
<tr class="odd">
<td>Output</td>
<td>Save to file — name it <code>parks_buffer_WGS84.gpkg</code> in your working folder</td>
</tr>
</tbody>
</table>
<ol start="4" type="1">
<li>Click <strong>Run</strong>.</li>
</ol>
<blockquote class="blockquote">
<p><strong>Warning:</strong> A 0.5 buffer run on WGS84 data is measured in <strong>degrees</strong>, not miles. At Philadelphia’s latitude (~40° N), 1 degree of longitude is approximately 53 miles. A buffer of 0.5 degrees is therefore roughly <strong>26 miles wide</strong> — not half a mile. The result covers a region far larger than the entire city. You should never use degree-unit buffers for distance analysis. This step exists only to make that error visible and unforgettable.</p>
</blockquote>
<ol start="5" type="1">
<li>When the tool finishes, <code>parks_buffer_WGS84</code> appears in the Layers panel. Note how the buffer polygons dwarf the city. Philadelphia is almost entirely contained within a single buffer zone.</li>
</ol>
<p><em>[Figure: WGS84 0.5-degree buffer covering a region far larger than Philadelphia — the “wrong” buffer]</em></p>
</section>
<section id="use-the-measure-tool-to-document-the-distortion" class="level3">
<h3 class="anchored" data-anchor-id="use-the-measure-tool-to-document-the-distortion">Use the Measure tool to document the distortion</h3>
<ol start="6" type="1">
<li>On the toolbar, click the <strong>Measure Line</strong> tool (ruler icon), or go to <strong>View ▸ Measure ▸ Measure Line</strong>. In the measure window that appears, set units to <strong>Miles</strong>.</li>
<li>Click one edge of a buffer polygon, then double-click the opposite edge. Note the approximate diameter in miles. It will be close to 53 miles — confirming that “0.5 degrees” at this latitude is nowhere near 0.5 miles.</li>
<li>Right-click to stop measuring. Write this value down; you will compare it to the correct buffer in Part 3.</li>
</ol>
<hr>
</section>
</section>
<section id="part-3-reproject-the-data-and-run-the-buffer-correctly" class="level2">
<h2 class="anchored" data-anchor-id="part-3-reproject-the-data-and-run-the-buffer-correctly">Part 3: Reproject the data and run the buffer correctly</h2>
<section id="permanently-reproject-to-pa-state-plane-south-epsg2272" class="level3">
<h3 class="anchored" data-anchor-id="permanently-reproject-to-pa-state-plane-south-epsg2272">Permanently reproject to PA State Plane South (EPSG:2272)</h3>
<ol type="1">
<li>In the <strong>Layers</strong> panel, right-click <code>PPR_properties</code> and select <strong>Export ▸ Save Features As…</strong></li>
</ol>
<blockquote class="blockquote">
<p><strong>Note:</strong> This is how QGIS permanently reprojects a layer — it writes a new file in the target CRS. The original file on disk is unchanged. Do not confuse this with changing the project CRS (which only affects display) or with <strong>Layer ▸ Set Layer CRS</strong> (which relabels a layer without converting any coordinates — analogous to ArcGIS Pro’s “Define Projection” mistake).</p>
</blockquote>
<ol start="2" type="1">
<li>In the <strong>Save Vector Layer as…</strong> dialog, set:</li>
</ol>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Format</td>
<td>GeoPackage</td>
</tr>
<tr class="even">
<td>File name</td>
<td><code>parks_StatePlane.gpkg</code> (in your working folder)</td>
</tr>
<tr class="odd">
<td>CRS</td>
<td>Click the globe icon; type <code>2272</code> in the filter; select <strong>NAD83 / Pennsylvania South</strong> (EPSG:2272); click <strong>OK</strong></td>
</tr>
<tr class="even">
<td>Add saved file to map</td>
<td>Checked</td>
</tr>
</tbody>
</table>
<ol start="3" type="1">
<li>Click <strong>OK</strong>. <code>parks_StatePlane</code> appears in the Layers panel.</li>
<li>Repeat for <code>phl_tracts_acs</code>, saving as <code>tracts_StatePlane.gpkg</code> with CRS EPSG:2272.</li>
</ol>
<p><em>[Figure: Save Features As dialog with EPSG:2272 selected as the target CRS]</em></p>
</section>
<section id="verify-the-reprojection" class="level3">
<h3 class="anchored" data-anchor-id="verify-the-reprojection">Verify the reprojection</h3>
<ol start="5" type="1">
<li>Right-click <code>parks_StatePlane</code> ▸ <strong>Properties ▸ Information</strong>. Confirm the CRS now shows <strong>EPSG:2272 — NAD83 / Pennsylvania South</strong>.</li>
<li>Watch the coordinate readout at the bottom-center of the QGIS window as you move your cursor over <code>parks_StatePlane</code>. Values should now be in the hundreds of thousands (US survey feet from the State Plane origin), not decimal degrees.</li>
</ol>
</section>
<section id="set-the-project-crs-to-epsg2272" class="level3">
<h3 class="anchored" data-anchor-id="set-the-project-crs-to-epsg2272">Set the project CRS to EPSG:2272</h3>
<ol start="7" type="1">
<li>Click the CRS button at the bottom-right of the window (or <strong>Project ▸ Properties ▸ CRS</strong>). Type <code>2272</code> in the filter, select <strong>NAD83 / Pennsylvania South</strong>, and click <strong>OK</strong>. The project now displays in State Plane feet.</li>
</ol>
</section>
<section id="run-the-buffer-in-feet" class="level3">
<h3 class="anchored" data-anchor-id="run-the-buffer-in-feet">Run the Buffer in feet</h3>
<ol start="8" type="1">
<li>In the <strong>Processing Toolbox</strong>, search <code>buffer</code> and open <strong>Buffer</strong> again. Set:</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Input layer</td>
<td><code>parks_StatePlane</code></td>
</tr>
<tr class="even">
<td>Distance</td>
<td><code>2640</code></td>
</tr>
<tr class="odd">
<td>Segments</td>
<td>5</td>
</tr>
<tr class="even">
<td>Dissolve result</td>
<td>Checked</td>
</tr>
<tr class="odd">
<td>Output</td>
<td><code>parks_buffer_StatePlane.gpkg</code> in your working folder</td>
</tr>
</tbody>
</table>
<p>2,640 feet = 0.5 miles exactly. One mile = 5,280 feet; half a mile = 2,640 feet.</p>
<ol start="9" type="1">
<li>Click <strong>Run</strong>.</li>
</ol>
<p><em>[Figure: NAD83 PA State Plane buffer at 2,640 feet — sensible half-mile rings around Philadelphia parks]</em></p>
</section>
<section id="measure-and-compare" class="level3">
<h3 class="anchored" data-anchor-id="measure-and-compare">Measure and compare</h3>
<ol start="10" type="1">
<li>Use the <strong>Measure Line</strong> tool again (units: Miles). Measure across a buffer ring. The diameter should be approximately 1 mile (0.5 miles each side). Record this value alongside the WGS84 measurement from Part 2.</li>
</ol>
<hr>
</section>
</section>
<section id="part-4-compare-the-two-buffers-in-a-print-layout" class="level2">
<h2 class="anchored" data-anchor-id="part-4-compare-the-two-buffers-in-a-print-layout">Part 4: Compare the two buffers in a Print Layout</h2>
<ol type="1">
<li>Go to <strong>Project ▸ New Print Layout</strong>. Name it <code>Buffer_Comparison</code> and click <strong>OK</strong>. The Print Layout designer opens.</li>
<li>Set page size to <strong>Letter Landscape</strong>: in the <strong>Layout</strong> panel on the right, under <strong>Page</strong>, set <strong>Orientation</strong> to <strong>Landscape</strong>.</li>
<li>Add the first map frame: <strong>Add Item ▸ Add Map</strong>. Draw a rectangle covering roughly the left half of the page. In the <strong>Item Properties</strong> panel, set the <strong>CRS</strong> to EPSG:4326 (WGS 84) by clicking the globe icon. This frame will show the WGS84 buffer. Set a fixed scale of approximately <strong>1:500,000</strong> so the enormous degree-unit buffer is visible.</li>
<li>In the Layers panel (back in the main QGIS window), turn on <code>parks_buffer_WGS84</code> and <code>phl_tracts_acs</code>; turn off the State Plane layers. Return to the Print Layout and click <strong>Set Map Extent to Match Main Canvas</strong> in the Item Properties if needed.</li>
<li>Add a second map frame covering the right half of the page. Set its CRS to EPSG:2272. Set the same scale (~1:100,000 works for the city extent). This frame will show the correct State Plane buffer.</li>
<li>For each map frame, use <strong>Add Item ▸ Add Label</strong> to add titles: “WGS84 Buffer (Wrong — 0.5 degrees)” and “State Plane Buffer (Correct — 2,640 feet / 0.5 miles).”</li>
<li>Add <strong>Add Item ▸ Add Scale Bar</strong> and <strong>Add Item ▸ Add North Arrow</strong> to each map frame. Add a title label with your name and date.</li>
<li>Export: <strong>Layout ▸ Export as PDF…</strong> Save as <code>Lab02a_buffer_comparison.pdf</code> in your working folder.</li>
</ol>
<p><em>[Figure: Finished Print Layout — left panel shows the enormous WGS84 degree buffer; right panel shows the correctly-sized half-mile State Plane buffer]</em></p>
<hr>
</section>
<section id="part-5-estimate-children-with-park-access-by-poverty-quintile" class="level2">
<h2 class="anchored" data-anchor-id="part-5-estimate-children-with-park-access-by-poverty-quintile">Part 5: Estimate children with park access by poverty quintile</h2>
<section id="prepare-tract-areas-for-areal-interpolation" class="level3">
<h3 class="anchored" data-anchor-id="prepare-tract-areas-for-areal-interpolation">Prepare tract areas for areal interpolation</h3>
<ol type="1">
<li>Switch back to the main QGIS map canvas. Make sure <code>tracts_StatePlane</code> is loaded and the project CRS is EPSG:2272.</li>
<li>Open the <strong>Attribute Table</strong> for <code>tracts_StatePlane</code> (right-click ▸ <strong>Open Attribute Table</strong>, or F6). Check whether a full-tract area field (<code>AREA_FULL</code>) already exists. If not, proceed to step 3. If it does, skip to step 5.</li>
<li>Toggle editing on (pencil icon at the top of the Attribute Table). Click the <strong>Field Calculator</strong> (abacus icon). Create a new field:</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Setting</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Create new field</td>
<td>Checked</td>
</tr>
<tr class="even">
<td>Output field name</td>
<td><code>AREA_FULL</code></td>
</tr>
<tr class="odd">
<td>Output field type</td>
<td>Decimal number (real)</td>
</tr>
<tr class="even">
<td>Expression</td>
<td><code>$area</code></td>
</tr>
</tbody>
</table>
<p><code>$area</code> returns the polygon area in the units of the layer’s CRS — here, square US survey feet. Click <strong>OK</strong>.</p>
<ol start="4" type="1">
<li>Toggle editing off and save changes.</li>
</ol>
</section>
<section id="intersect-the-correct-buffer-with-census-tracts" class="level3">
<h3 class="anchored" data-anchor-id="intersect-the-correct-buffer-with-census-tracts">Intersect the correct buffer with census tracts</h3>
<ol start="5" type="1">
<li>In the <strong>Processing Toolbox</strong>, search <code>intersection</code> and open <strong>Intersection</strong> (Vector overlay). Set:</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Input layer</td>
<td><code>parks_buffer_StatePlane</code></td>
</tr>
<tr class="even">
<td>Overlay layer</td>
<td><code>tracts_StatePlane</code></td>
</tr>
<tr class="odd">
<td>Output</td>
<td><code>buffer_tracts_intersect.gpkg</code> in your working folder</td>
</tr>
</tbody>
</table>
<ol start="6" type="1">
<li>Click <strong>Run</strong>. The output contains the portions of census tracts that fall inside the park buffer, carrying all original tract attributes.</li>
</ol>
<blockquote class="blockquote">
<p><strong>Public health note:</strong> This intersection clips tract polygons at the buffer boundary. For tracts only partially inside the buffer, you will estimate child population by assuming it is distributed uniformly across the tract’s area — a method called areal interpolation. This is an approximation. It is imperfect but standard practice when individual-level data are unavailable.</p>
</blockquote>
</section>
<section id="calculate-clipped-area-and-estimated-children-in-the-buffer" class="level3">
<h3 class="anchored" data-anchor-id="calculate-clipped-area-and-estimated-children-in-the-buffer">Calculate clipped area and estimated children in the buffer</h3>
<ol start="7" type="1">
<li>Open the <strong>Attribute Table</strong> for <code>buffer_tracts_intersect</code>. Toggle editing on. Use the <strong>Field Calculator</strong> to create a new field:</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Setting</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Output field name</td>
<td><code>AREA_CLIP</code></td>
</tr>
<tr class="even">
<td>Output field type</td>
<td>Decimal number (real)</td>
</tr>
<tr class="odd">
<td>Expression</td>
<td><code>$area</code></td>
</tr>
</tbody>
</table>
<ol start="8" type="1">
<li>Create another new field to estimate children inside the buffer:</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Setting</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Output field name</td>
<td><code>CHILDREN_IN_BUF</code></td>
</tr>
<tr class="even">
<td>Output field type</td>
<td>Decimal number (real)</td>
</tr>
<tr class="odd">
<td>Expression</td>
<td><code>"CHILD_POP" * ("AREA_CLIP" / "AREA_FULL")</code></td>
</tr>
</tbody>
</table>
<p>This apportions each tract’s child population proportional to the share of that tract’s area inside the buffer.</p>
<ol start="9" type="1">
<li>Toggle editing off and save.</li>
</ol>
</section>
<section id="summarize-by-poverty-quintile" class="level3">
<h3 class="anchored" data-anchor-id="summarize-by-poverty-quintile">Summarize by poverty quintile</h3>
<ol start="10" type="1">
<li>In the <strong>Processing Toolbox</strong>, search <code>statistics by categories</code> and open <strong>Statistics by categories</strong> (Vector analysis). Set:</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Input vector layer</td>
<td><code>buffer_tracts_intersect</code></td>
</tr>
<tr class="even">
<td>Field to calculate statistics on</td>
<td><code>CHILDREN_IN_BUF</code></td>
</tr>
<tr class="odd">
<td>Field(s) with categories</td>
<td><code>POV_QUINTILE</code></td>
</tr>
<tr class="even">
<td>Output</td>
<td><code>quintile_buffer_summary.gpkg</code></td>
</tr>
</tbody>
</table>
<ol start="11" type="1">
<li>Click <strong>Run</strong>. Open the output table and note the <code>sum</code> column — this is estimated children in the buffer for each poverty quintile.</li>
<li>Repeat <strong>Statistics by categories</strong> on <code>tracts_StatePlane</code>, field <code>CHILD_POP</code>, category <code>POV_QUINTILE</code> to get total children per quintile citywide.</li>
<li>Open a spreadsheet or use the QGIS <strong>Field Calculator</strong> to compute percent access: divide each quintile’s buffer sum by its citywide total and multiply by 100. Fill in the table below.</li>
</ol>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Poverty quintile</th>
<th>Total children in city</th>
<th>Children in park buffer</th>
<th>% with park access</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1 (lowest poverty)</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>2</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>3</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>4</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>5 (highest poverty)</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="apply-graduated-symbology-to-visualize-access-by-poverty-quintile" class="level3">
<h3 class="anchored" data-anchor-id="apply-graduated-symbology-to-visualize-access-by-poverty-quintile">Apply graduated symbology to visualize access by poverty quintile</h3>
<ol start="14" type="1">
<li>Right-click <code>tracts_StatePlane</code> ▸ <strong>Properties ▸ Symbology</strong>. Change the render type from <strong>Single Symbol</strong> to <strong>Graduated</strong>.</li>
<li>Set <strong>Value</strong> to <code>POV_QUINTILE</code>, <strong>Classes</strong> to 5, <strong>Mode</strong> to <strong>Equal Interval</strong>, and choose a <strong>ColorBrewer</strong> sequential ramp (e.g., <strong>YlOrRd</strong> or <strong>Blues</strong>). Click <strong>Classify</strong>, then <strong>OK</strong>.</li>
<li>This map shows poverty quintile distribution. Consider adding a second map showing <code>CHILDREN_IN_BUF</code> as a graduated layer on <code>buffer_tracts_intersect</code> to visualize where children with park access live.</li>
</ol>
<p><em>[Figure: Graduated symbology on census tracts by POV_QUINTILE, with park buffer overlay]</em></p>
<hr>
</section>
</section>
<section id="deliverables" class="level2">
<h2 class="anchored" data-anchor-id="deliverables">Deliverables</h2>
<p>Submit the following as one PDF or as directed by your instructor:</p>
<ol type="1">
<li><strong>Side-by-side buffer comparison PDF</strong> (<code>Lab02a_buffer_comparison.pdf</code>) — two map panels at equal scale showing the WGS84 buffer (wrong) and the State Plane buffer (correct), with labeled titles, scale bars, north arrows, and your name.</li>
<li><strong>Completed access table</strong> — the poverty quintile table from Part 5 with all five rows filled in. Screenshot or paste into your submission PDF.</li>
<li><strong>100-word written interpretation</strong> answering: Which quintile has the highest park access rate? The lowest? What does this pattern suggest about park equity in Philadelphia? Why is the WGS84 buffer invalid for this analysis? Label any AI-assisted portions.</li>
<li><strong>Your saved project file</strong> <code>Lab02a_Projections.qgz</code>.</li>
</ol>
<hr>
</section>
<section id="using-ai-in-this-lab" class="level2">
<h2 class="anchored" data-anchor-id="using-ai-in-this-lab">Using AI in this lab</h2>
<p><strong>Bounded AI task — interrogating a CRS definition:</strong></p>
<ol type="1">
<li>In QGIS, right-click any layer ▸ <strong>Properties ▸ Information</strong>. Scroll to the CRS section and copy the full CRS text block, including the PROJ string or WKT definition.</li>
<li>Paste it into Claude (claude.ai) with this prompt: “Here is a coordinate reference system definition. Is this geographic or projected? What are its linear units? Is it appropriate for measuring distances in Philadelphia, PA? Explain why or why not.”</li>
<li>Read the response critically. Does the AI correctly identify the units? Compare its answer to what you found at epsg.io. AI explains CRS text well — treat it as a scaffold, not an authority.</li>
</ol>
<p>You can also ask Claude: “Here is a QGIS expression I wrote to calculate children in the buffer: <code>"CHILD_POP" * ("AREA_CLIP" / "AREA_FULL")</code>. Is the logic correct for areal interpolation? What assumptions does it make?” Then evaluate whether the explanation matches what you learned in lab.</p>
<p><strong>Guardrails:</strong></p>
<ul>
<li>AI helps with <strong>explaining</strong> (what does this CRS definition mean?) and <strong>critiquing</strong> (is my projection choice reasonable?). It does not make analytic decisions for you.</li>
<li>AI does <strong>not</strong> select the right projection for your study area — you do.</li>
<li>AI does <strong>not</strong> interpret your equity findings — that requires your public health judgment.</li>
<li><strong>Never paste patient data, addresses, or any identifiable health information into a public AI tool.</strong> A CRS string or QGIS expression contains no PHI and is safe to share.</li>
<li>Label any AI-assisted text in your deliverables.</li>
</ul>
<hr>
</section>
<section id="arcgis-equivalents" class="level2">
<h2 class="anchored" data-anchor-id="arcgis-equivalents">ArcGIS equivalents</h2>
<p>Students using ArcGIS Pro can complete this workflow with the following equivalents. Full Pro and ArcGIS Online versions of this lab exist for those platforms.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>QGIS operation</th>
<th>ArcGIS Pro equivalent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Layer Properties ▸ Information (CRS)</td>
<td>Layer Properties ▸ Source ▸ Spatial Reference</td>
</tr>
<tr class="even">
<td>Project CRS button (bottom-right)</td>
<td>Map Properties ▸ Coordinate System</td>
</tr>
<tr class="odd">
<td>Project ▸ Properties ▸ CRS</td>
<td>Map Properties ▸ Coordinate System</td>
</tr>
<tr class="even">
<td>Export ▸ Save Features As… (with target CRS)</td>
<td>Analysis ▸ Tools ▸ <strong>Project</strong> tool (Data Management)</td>
</tr>
<tr class="odd">
<td>Processing ▸ Reproject Layer</td>
<td>Same <strong>Project</strong> tool</td>
</tr>
<tr class="even">
<td>Processing ▸ Buffer (native:buffer)</td>
<td>Analysis ▸ Tools ▸ <strong>Buffer</strong></td>
</tr>
<tr class="odd">
<td>View ▸ Measure ▸ Measure Line</td>
<td>Map tab ▸ Inquiry ▸ <strong>Measure</strong></td>
</tr>
<tr class="even">
<td>Processing ▸ Intersection</td>
<td>Analysis ▸ Tools ▸ <strong>Intersect</strong></td>
</tr>
<tr class="odd">
<td>Field Calculator (<code>$area</code>)</td>
<td>Field Calculator or Calculate Geometry</td>
</tr>
<tr class="even">
<td>Processing ▸ Statistics by categories</td>
<td>Analysis ▸ Tools ▸ <strong>Summary Statistics</strong></td>
</tr>
<tr class="odd">
<td>Project ▸ New Print Layout</td>
<td>Insert ▸ New Layout</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Key difference:</strong> ArcGIS Online computes buffers geodesically by default, so degree-unit errors are less likely to surface there. QGIS and ArcGIS Pro both perform planar buffering by default — the CRS of your data determines whether the result is valid. This makes CRS management more visible, and more important, in desktop GIS.</p>
</blockquote>
<hr>
</section>
<section id="check-your-understanding" class="level2">
<h2 class="anchored" data-anchor-id="check-your-understanding">Check your understanding</h2>
<ol type="1">
<li><p>A colleague sends you a shapefile of school locations in Philadelphia. You load it into QGIS and it displays correctly over an OpenStreetMap basemap. Does this confirm the layer’s CRS is correct for distance analysis? Why or why not?</p></li>
<li><p>What is the difference between <strong>Export ▸ Save Features As…</strong> (with a new target CRS) and <strong>Layer ▸ Set Layer CRS</strong> in QGIS? Which one actually converts coordinates, and when would misusing the second one damage your data?</p></li>
<li><p>You are asked to create a 1-kilometer buffer around all FQHC clinic locations in Philadelphia. Which EPSG code would you choose — EPSG:4326, EPSG:2272, or EPSG:26918 — and why? Is there more than one acceptable answer?</p></li>
<li><p>In the Print Layout you produced, the WGS84 buffer polygon extends far beyond the city limits. Explain in plain language why a “0.5-degree” buffer at Philadelphia’s latitude (~40° N) produces a result approximately 26 miles wide.</p></li>
<li><p>Your access table shows that census tracts in the highest-poverty quintile have a lower percentage of children with park access than tracts in the lowest-poverty quintile. List two alternative explanations for this pattern that do not involve park location — and identify what additional data you would need to evaluate each explanation.</p></li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/aquistbe\.github\.io\/UHC-Summer-Institute-IntroGIS-2026\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Introduction to GIS for Public Health | Urban Health Summer Institute</p>
</div>   
    <div class="nav-footer-center">
<p>Drexel University Dornsife School of Public Health</p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/aquistbe/UHC-Summer-Institute-IntroGIS-2026/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>© 2026 Alex Quistberg</p>
</div>
  </div>
</footer>




</body></html>